name: 🐛 Bug Report (react)
description: Report a bug for @dropdown-datepicker/react
labels: ["bug", "package:react"]
body:
    - type: input
      id: version
      attributes:
          label: Package version
          placeholder: e.g., 1.0.0
    - type: textarea
      id: description
      attributes:
          label: What’s the bug?
    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
